# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ComputerStore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ComputerStore
    pod 'SnapKit', '~> 4.0.0'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'SwiftyGif'
    pod 'SwiftKeychainWrapper'

end
